name: Build mpv-iina
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

env:
  CFLAGS: -mmacosx-version-min=10.12
  LDFLAGS: -mmacosx-version-min=10.12

jobs:
  release-osx:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Tab xjbeta/homebrew-mpv-iina
        run: brew tap xjbeta/homebrew-mpv-iina

      - name: Install mpv-iina
        run: brew install mpv-iina

      - name: Make deps folder
        run: mkdir deps

      - name: Run change_lib_dependencies.rb
        run: other/change_lib_dependencies.rb "$(brew --prefix)" "$(brew --prefix mpv-iina)/lib/libmpv.dylib"

      - name: dylibs LC_BUILD_VERSION
        run: for lib in deps/lib/*(.); do (echo $lib; otool -l $lib | grep -i LC_BUILD_VERSION -A 4); done
      - name: dylibs LC_VERSION_MIN_MACOSX
        run: for lib in deps/lib/*(.); do (echo $lib; otool -l $lib | grep -A 3 LC_VERSION_MIN_MACOSX); done
        

      - name: Archive libs
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: deps
          
