name: Build mpv-iina
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

env:
  CFLAGS: -mmacosx-version-min=10.12
  LDFLAGS: -mmacosx-version-min=10.12

jobs:
  release-osx:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install mpv-iina
        run: |
          brew tap xjbeta/homebrew-mpv-iina
          brew install mpv-iina

      - name: Run change_lib_dependencies.rb
        run: |
          mkdir deps
          other/change_lib_dependencies.rb "$(brew --prefix)" "$(brew --prefix mpv-iina)/lib/libmpv.dylib"

      - name: dylibs LC_BUILD_VERSION LC_VERSION_MIN_MACOSX
        run: |
          zsh -c 'for lib in deps/lib/*; do (echo $lib; otool -l $lib | grep -i LC_BUILD_VERSION -A 4); done'
          zsh -c 'for lib in deps/lib/*; do (echo $lib; otool -l $lib | grep -A 3 LC_VERSION_MIN_MACOSX); done'
        

      - name: Archive libs
        uses: actions/upload-artifact@v2
        with:
          name: deps
          path: deps/
          
